"""
T19 — star_restoration

Recombine the processed starless image with stars. Two modes:

blend: Weighted pixel math recombination of starless + star mask.
  - star_weight = 1.0: restore stars at original intensity.
  - star_weight < 1.0: reduce star prominence (e.g., 0.7 = stars at 70%).
    This effectively replaces a dedicated morphological star-reduction step.
  - Requires both images as FITS in working_dir (for Siril pixel math $stem$ vars).

synthstar: Replace original stars with synthetic perfect-profile stars
  generated by Siril from PSF measurements.
  - Eliminates coma, trailing, diffraction spikes from optics/tracking.
  - Best results when run on the LINEAR image before stretching (T14), using
    the synthstar output as the star layer to blend with the processed starless.
  - For typical workflows: run synthstar on the stretched pre-starnet image,
    use its output as the source_image for the star layer.

Backend: Siril CLI — `pm` (pixel math) for blend, `synthstar` for synthstar.

Important: Siril pixel math uses $stem$ notation — both FITS files must
reside in working_dir and be referenced by their stem (no extension, no path).
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Annotated

from langchain_core.messages import ToolMessage
from langchain_core.tools import tool
from langchain_core.tools.base import InjectedToolCallId
from langgraph.prebuilt import InjectedState
from langgraph.types import Command
from pydantic import BaseModel, Field

from muphrid.graph.state import AstroState
from muphrid.tools._siril import fits_nlayers, run_siril_script


# ── Pydantic input schema ──────────────────────────────────────────────────────

class BlendOptions(BaseModel):
    star_weight: float = Field(
        default=1.0,
        description=(
            "Blend weight for the star layer (0.0–1.0+). "
            "1.0: restore stars at full intensity. "
            "0.6–0.9: reduce star prominence while keeping them visible. "
            "< 0.5: heavy star suppression for nebula-focused compositions. "
            "Values slightly above 1.0 (1.1–1.2) can compensate if stars appear "
            "dim after aggressive nebulosity processing."
        ),
    )


class SynthstarOptions(BaseModel):
    source_image_path: str = Field(
        description=(
            "Absolute path to the image used as the source for synthetic star "
            "generation. For best quality: the stretched image before star removal "
            "(pre-T15). Siril's synthstar detects stars in this image and generates "
            "synthetic Moffat/Gaussian profiles matching each star's measured PSF."
        )
    )


class StarRestorationInput(BaseModel):
    mode: str = Field(
        default="blend",
        description=(
            "blend: weighted pixel math recombination with original star mask. "
            "Use star_weight to control star prominence. "
            "synthstar: replace original stars with synthetic perfect-profile stars. "
            "Use when original stars have coma, trailing, or diffraction issues."
        ),
    )
    blend_options: BlendOptions | None = Field(
        default=None,
        description="Required when mode=blend.",
    )
    synthstar_options: SynthstarOptions | None = Field(
        default=None,
        description="Required when mode=synthstar.",
    )


# ── LangChain tool ─────────────────────────────────────────────────────────────

@tool(args_schema=StarRestorationInput)
def star_restoration(
    mode: str = "blend",
    blend_options: BlendOptions | None = None,
    synthstar_options: SynthstarOptions | None = None,
    tool_call_id: Annotated[str, InjectedToolCallId] = None,
    state: Annotated[AstroState, InjectedState] = None,
) -> Command:
    """
    Blend a star mask back into a starless image.

    Blend mode (default):
      Uses Siril pixel math: $starless$ + $starmask$ * star_weight
      Requires: both FITS files in working_dir.
      star_weight < 1.0 reduces star prominence — an effective star reduction
      technique that preserves more natural star color than morphological methods.

    Synthstar mode:
      Siril detects stars in source_image, measures each star's PSF (FWHM,
      ellipticity, hue), and generates a synthetic Moffat profile replacement.
      Eliminates optical aberrations (coma, trailing, spikes) from the star layer.
      Best results: use source_image = the stretched pre-starnet image.
    """
    working_dir = state["dataset"]["working_dir"]
    starless_image_path = state["paths"]["starless_image"]
    star_mask_path_from_state = state["paths"]["star_mask"]

    starless_path = Path(starless_image_path)
    if not starless_path.exists():
        raise FileNotFoundError(f"Starless image not found: {starless_image_path}")

    if fits_nlayers(starless_path) < 3:
        raise ValueError(
            f"star_restoration requires a color (3-channel RGB) starless image, but "
            f"{starless_path.name} is monochrome. "
            "Recombining a mono starless with a color star mask produces a mono result "
            "with no color information. "
            "Trace back to T15 star_removal — StarNet must output color. "
            "If T15 raised no error, check whether T16–T18 inadvertently converted "
            "the image to mono."
        )

    if mode == "blend" and blend_options is None:
        blend_options = BlendOptions()
    if mode == "synthstar" and synthstar_options is None:
        raise ValueError("synthstar_options (including source_image_path) is required for mode=synthstar.")

    starless_stem = starless_path.stem
    output_stem = f"{starless_stem}_restored"

    if mode == "blend":
        # Use star mask from state
        mask_path = Path(star_mask_path_from_state)
        if not mask_path.exists():
            raise FileNotFoundError(f"Star mask not found: {star_mask_path_from_state}")

        # Both FITS must be in working_dir for $stem$ pixel math to resolve
        if mask_path.parent.resolve() != Path(working_dir).resolve():
            raise ValueError(
                f"Star mask must be in working_dir ({working_dir}) for Siril "
                f"pixel math. Got: {mask_path.parent}"
            )
        if starless_path.parent.resolve() != Path(working_dir).resolve():
            raise ValueError(
                f"Starless image must be in working_dir ({working_dir}) for Siril "
                f"pixel math. Got: {starless_path.parent}"
            )

        mask_stem = mask_path.stem
        weight = blend_options.star_weight  # type: ignore[union-attr]
        expression = f'"${starless_stem}$ + ${mask_stem}$ * {weight}"'

        commands = [
            f"pm {expression}",
            f"save {output_stem}",
        ]

    else:
        # synthstar mode
        source_path = Path(synthstar_options.source_image_path)  # type: ignore[union-attr]
        if not source_path.exists():
            raise FileNotFoundError(f"Source image not found: {synthstar_options.source_image_path}")  # type: ignore[union-attr]

        source_stem = source_path.stem
        commands = [
            f"load {source_stem}",
            "synthstar",
            f"save {output_stem}",
        ]

    run_siril_script(commands, working_dir=working_dir, timeout=120)

    output_path = Path(working_dir) / f"{output_stem}.fit"
    if not output_path.exists():
        output_path = Path(working_dir) / f"{output_stem}.fits"
    if not output_path.exists():
        raise FileNotFoundError(f"star_restoration did not produce: {output_path}")

    summary: dict = {
        "output_path": str(output_path),
        "mode": mode,
        "starless_image": str(starless_image_path),
    }
    if mode == "blend":
        summary["star_mask"] = str(star_mask_path_from_state)
        summary["star_weight"] = blend_options.star_weight  # type: ignore[union-attr]
    elif mode == "synthstar":
        summary["source_image"] = str(synthstar_options.source_image_path)  # type: ignore[union-attr]

    return Command(update={
        "paths": {**state["paths"], "current_image": str(output_path)},
        "messages": [ToolMessage(content=json.dumps(summary, indent=2, default=str), tool_call_id=tool_call_id)],
    })
